server:
  port: 0

spring:
  application:
    name: order-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/order_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password:

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation.level: read_committed

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        linger.ms: 10
        batch.size: 32768

    listener:
      ack-mode: manual
      concurrency: 3

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://admin:1234@localhost:9000}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: full
      okhttp:
        enabled: true
eureka:

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

internal:
  item:
    stock:
      retry:
        max-attempts: 3
        delay: 100
        multiplier: 2.0
        max-delay: 1000
        non-retryable-codes:
          - I001
          - I002
          - I003

logging:
  level:
    app.backend.order.client: DEBUG
    feign: DEBUG